#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
    libpcap-dev \
    libturbojpeg0
sudo python3 -m pip install uv
sudo uv pip install --system --requirements requirements.txt
pre-commit install
